"""empty message

Revision ID: 07c9737cd7bf
Revises: e1d54080707f
Create Date: 2024-12-20 14:47:52.497748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07c9737cd7bf"
down_revision: Union[str, None] = "e1d54080707f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "summarizing_model",
            sa.String(),
            server_default="models/gemini-1.5-flash-latest",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "summarizing_model")
    # ### end Alembic commands ###
