"""empty message

Revision ID: 0afa420d867e
Revises: ed5162e4188e
Create Date: 2025-06-21 11:17:45.556916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0afa420d867e"
down_revision: Union[str, None] = "ed5162e4188e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "summarizing_model",
        existing_type=sa.VARCHAR(),
        server_default="gemini-2.5-flash",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "summarizing_model",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'gemini-2.0-flash'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
