"""add yt_transcript_source to users

Revision ID: 10c9ae0e381a
Revises: c27e3620d906
Create Date: 2026-05-23 14:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "10c9ae0e381a"
down_revision: Union[str, None] = "c27e3620d906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "yt_transcript_source",
            sa.String(),
            server_default="api",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "yt_transcript_source")
    # ### end Alembic commands ###
