"""empty message

Revision ID: 198b7ed11f80
Revises: 437d9635461c
Create Date: 2024-10-12 12:17:59.738374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "198b7ed11f80"
down_revision: Union[str, None] = "437d9635461c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "use_yt_transcription",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_yt_transcription")
    # ### end Alembic commands ###
