"""empty message

Revision ID: 26c5df468f24
Revises: 38ba859a4715
Create Date: 2024-10-14 14:32:37.746993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26c5df468f24"
down_revision: Union[str, None] = "38ba859a4715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "target_language",
        existing_type=sa.VARCHAR(),
        server_default="English",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "target_language",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
