"""empty message

Revision ID: 296e8837ca37
Revises: c1f28a6c8650
Create Date: 2024-10-14 16:09:47.193841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "296e8837ca37"
down_revision: Union[str, None] = "c1f28a6c8650"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "use_transcription",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "use_translator",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "target_language",
            sa.String(),
            server_default="English",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "use_yt_transcription",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_yt_transcription")
    op.drop_column("users", "target_language")
    op.drop_column("users", "use_translator")
    op.drop_column("users", "use_transcription")
    # ### end Alembic commands ###
