"""empty message

Revision ID: 35e967a89382
Revises: 07c9737cd7bf
Create Date: 2024-12-24 15:25:50.157311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35e967a89382"
down_revision: Union[str, None] = "07c9737cd7bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "prompt_key_for_summary",
            sa.String(),
            server_default="basic_prompt_for_transcript",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "prompt_key_for_summary")
    # ### end Alembic commands ###
