"""empty message

Revision ID: 38ba859a4715
Revises: 198b7ed11f80
Create Date: 2024-10-14 13:44:21.643439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38ba859a4715"
down_revision: Union[str, None] = "198b7ed11f80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "approved",
        existing_type=sa.BOOLEAN(),
        server_default="False",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "use_transcription",
        existing_type=sa.BOOLEAN(),
        server_default="False",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "use_translator",
        existing_type=sa.BOOLEAN(),
        server_default="False",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "use_translator",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "use_transcription",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "approved",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
