"""add thinking_level to users

Revision ID: 4674e2a53a5c
Revises: 6bb4ed473ffd
Create Date: 2026-05-26 16:19:36.047023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4674e2a53a5c"
down_revision: Union[str, None] = "6bb4ed473ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "thinking_level",
            sa.String(),
            server_default="MINIMAL",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "thinking_level")
    # ### end Alembic commands ###
