"""empty message

Revision ID: 7d6c441557e8
Revises: 35e967a89382
Create Date: 2025-02-05 16:59:58.660958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d6c441557e8"
down_revision: Union[str, None] = "35e967a89382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "summarizing_model",
        existing_type=sa.VARCHAR(),
        server_default="gemini-2.0-flash",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "summarizing_model",
        existing_type=sa.VARCHAR(),
        server_default=sa.text(
            "'models/gemini-1.5-flash-latest'::character varying"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
