"""drop yt_transcription from users

Revision ID: a768d66b5971
Revises: ac58b3f071ef
Create Date: 2026-06-12 11:06:50.862468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a768d66b5971"
down_revision: Union[str, None] = "ac58b3f071ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_yt_transcription")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "use_yt_transcription",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
