"""drop yt_transcript_source from users

Revision ID: ac58b3f071ef
Revises: 4674e2a53a5c
Create Date: 2026-06-01 09:59:51.059445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ac58b3f071ef"
down_revision: Union[str, None] = "4674e2a53a5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "yt_transcript_source")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "yt_transcript_source",
            sa.String(),
            server_default="api",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
