"""empty message

Revision ID: af77dea001da
Revises: 0797d20d7869
Create Date: 2026-04-08 12:17:47.095161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "af77dea001da"
down_revision: Union[str, None] = "0797d20d7869"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "summarizing_model",
        existing_type=sa.VARCHAR(),
        server_default="gemini-3-flash-preview",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "summarizing_model",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'gemini-2.5-flash'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
