name: Lint

on: pull_request

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint /src

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1 # https://docs.astral.sh/ruff/integrations/#github-actions

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Run mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: "."
          mypy_flags: "--config-file pyproject.toml"

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
